browser = chrome

qaurl = https://freelance-learn-automation.vercel.app

implicitWait = 10

pageloadTime =60

screenShotOnFailure = true

screenShotOnSuccess = true

headless = false

gridURL = http://hub.lambdatest.com

highlight =yes

username=tejarocks555@gmail.com
password=admin@123

retry = 1





